### PR TITLE
Better switch reinstall error handling

### LINKED ISSUE #317: Switch reinstall reports success whereas reinstall_helper fails
This happens when the switch console is not responding and `--wait-ready` is `false`

```
./hhfab vlab switch reinstall --mode reboot --yes -v
...
07:34:46 DBG sse-c4632-02: 07:34:46 INF sse-c4632-02: Entering OS Install Mode...
07:34:46 INF Switch placed into NOS Install Mode name=sse-c4632-02
07:37:41 DBG s5248-05: 07:37:41 ERR serial: failed to run command: exit status 1
07:37:41 INF Switch placed into NOS Install Mode name=s5248-05
07:37:41 INF All switches placed into NOS Install Mode took=5m11.100456022s
```

### PR DESCRIPTION
**Pull request by pau-hedgehog**
Refactor vlabhelpers_reinstall.exp and improve error propagation

Fixes #317

### CODE REVIEW

File: pkg/hhfab/vlabhelpers.go [hunk 1]
```diff
@@ -344,10 +344,23 @@ func (c *Config) VLABSwitchReinstall(ctx context.Context, opts SwitchReinstallOp
 				defer mu.Unlock()
 
 				var exitErr *exec.ExitError
-				if errors.As(err, &exitErr) && errors.Is(ctx.Err(), context.DeadlineExceeded) {
+				if errors.As(err, &exitErr) {
+					switch exitErr.ExitCode() {
+					case 1: // ERROR_CONSOLE
```
Comment (edipascale) [inline pkg/hhfab/vlabhelpers.go:349]: I would:
* define constants for the error codes;
* declare the errors, e.g. `var consoleError = errors.New("Connection to console failed")`
* declare a wrapper function that takes the switch name and the exit code and returns the wrapped error
* get rid of the nolint messages as they are no longer needed

**Review by Frostman — APPROVED** [review]
