### PR TITLE
fix: ensure vfio_pci driver is loaded

### LINKED ISSUE #539: Automatically load vfio-pci
```
02:14:02 ERR preparing passthrough: binding device 0000:32:00.0 to vfio-pci: opening new_id file to bind to vfio-pci for 0000:32:00.0: open /sys/bus/pci/drivers/vfio-pci/
new_id: no such file or directory 
```

We should just run

```
sudo modprobe vfio_pci
```

### PR DESCRIPTION
**Pull request by mrbojangles3**
closes #539

### CODE REVIEW

File: pkg/hhfab/cmdhelpers.go [hunk 1]
```diff
@@ -129,6 +130,10 @@ func PreparePassthrough(_ context.Context, devs []string) error {
 	}
 
 	slog.Debug("Preparing devices for passthrough", "devices", devs)
+	cmd := exec.Command("modprobe", "vfio_pci")
+	if err := cmd.Run(); err != nil {
+		return fmt.Errorf("cannot insert vfio_pci: %w", err)
```
Comment (Frostman) [inline pkg/hhfab/cmdhelpers.go:135]: nitpicking: Is insert a right word here?

**Review by Frostman — APPROVED** [review]

File: pkg/hhfab/cmdhelpers.go (hunk 1 above)
Comment (mrbojangles3) [reply pkg/hhfab/cmdhelpers.go:135]: In my mind I was thinking of the old `insmod` command. The manpage for `modprobe` says it, "add or removes a module from the Linux kernel", the `-a` description says "insert all module names on the command line". I am okay with "cannot insert vfio_pci", or "cannot add vfio_pci".
